### ISSUE TITLE
Wrapper module for the library?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/webform2pdf#5]
On my rainy day list is bundling libraries for the Print module -- one of which would be the TCPDF library. 

https://github.com/backdrop-contrib/print/issues/13

Maybe we could do that as a wrapper module and relevant modules could depend on that wrapper rather than individually bundling the library? Then (as I understand the licensing) the wrapper module could also be licensed as `GPL-3.0` but we could still keep the regular modules as `GPL-2.0-or-later`.

**Comment by bugfolder** [comment]
Makes sense to do. Figuring out how to gracefully unbundle for existing users will be needed.

**Comment by bugfolder** [comment]
Proposed plan of action:

1. Prepare and release the [TCPDF library module](https://github.com/backdrop-contrib/tcpdf). [DONE]
2. In next bugfix release, add a status report warning that future versions of Webform2PDF will require the TCPDF module (only if that module isn't present+enabled). This will (one hopes) encourage site administrators to download and enable the module. [DONE]
3. After a decent interval (3 months? Which would be ~24 Jan 2023), create a new minor release that requires TCPDF module and no longer includes the bundled library. (And then, since the Drupal module was GPL2, and I wrote all the Backdrop code and can re-license my own changes, we can set this module back to GPL2 (though TCPDF will continue to be LGPL3, so its module will be GPL3). [DONE]
